#!/usr/bin/env bun

const { execSync } = require('child_process');

function runCommand(command) {
  try {
    execSync(command, { stdio: 'inherit' });
    return true;
  } catch (error) {
    console.error(`Error running command: ${command}`);
    return false;
  }
}

function main() {
  console.log('Running pre-commit checks...');

  const commandToRun = 'bun run format';

  if (!runCommand(commandToRun)) {
    console.error(
      'Error while running `bun run format` command. Aborting commit.'
    );
    process.exit(1);
  }

  console.log('Successfully formatted source code. Commit allowed.');
}

if (require.main === module) {
  main();
}
